---
application:
  name: "innexiarenamebot"
  project: "renamebot"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "innexiarenamebot"
  version: "8.0"
routers:
- name: "main-innexiarenamebot"
  routes:
  - application_name: "innexiarenamebot"
    paths:
    - "/*"
